version: "3"

services:
    traefik:
        image: traefik:latest
        restart: always
        command: --api --docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - stevendev
networks:
    zingdev:
        driver: bridge
