version: "3"

services:
    traefik:
        image: traefik:latest
        restart: always
        command: --api --docker
        restart: always
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - dev
networks:
    dev:
        driver: bridge
