version: "3"

services:
  traefik:
    image: traefik:latest
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "${WEBPORT}:80"
      - "${TRAEFIKAPIPORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev

networks:
  dev:
    driver: bridge
